AM_Spotify/Models/Autenticacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AM_Spotify.Models
{
    public class Autenticacao
    {
        public bool HasToken { get; set; }
    }
}

AM_Spotify/Models/PlayList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AM_Spotify.Models
{
    public class PlayList
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public string Criador { get; set; }
        public string Link { get; set; }
    }
}

AM_Spotify/Models/Track.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AM_Spotify.Models
{
    public class Track
    {
        public string Nome { get; set; }
        public string Album { get; set; }
        public string Artista { get; set; }
    }

}

AM_Spotify/Controllers/AuthController.cs
using AM_Spotify.Config;
using AM_Spotify.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_Spotify.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Index()
        {
            string code = HttpContext.Request.QueryString["code"];
            GerarToken(code);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return Redirect(@"https://accounts.spotify.com/authorize/?" + 
                "client_id=" + Spotify_Config.ClientID + "&response_type=code" +
                "&redirect_uri=" + Spotify_Config.RedirectUri + 
                "&scope=user-read-private%20user-read-email%20playlist-modify-private%20playlist-modify-public");
        }

        private void GerarToken(string code)
        {
            SpotifyService spotifyService = new SpotifyService();
            spotifyService.GenerateToken(code);
        }
        
    }
}

AM_Spotify/Controllers/HomeController.cs
using AM_Spotify.Models;
using AM_Spotify.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_Spotify.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(ApiManager.GetKey(ApiManager.Spotify)))
            {
                return RedirectToAction("Index", "Login");
            }

            return View();
        }

        public ActionResult About()
        {
            if (string.IsNullOrEmpty(ApiManager.GetKey(ApiManager.Spotify)))
            {
                return RedirectToAction("Index", "Login");
            }

            ViewBag.Message = "Objetivos do trabalho.";

            return View();
        }

        public ActionResult Contact()
        {
            if (string.IsNullOrEmpty(ApiManager.GetKey(ApiManager.Spotify)))
            {
                return RedirectToAction("Index", "Login");
            }

            ViewBag.Message = "Email: magmapt@gmail.com";

            return View();
        }
    }
}

AM_Spotify/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_Spotify.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {

            return View();
        }
    }
}

AM_Spotify/Controllers/PlayListController.cs
using AM_Spotify.Models;
using AM_Spotify.Services;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AM_Spotify.Controllers
{
    public class PlayListController : Controller
    {
        // GET: PlayList
        public ActionResult Index()
        {
            string token = ApiManager.GetKey(ApiManager.Spotify);
            bool hasToken = !string.IsNullOrEmpty(token);

            if (!hasToken)
            {
                return RedirectToAction("Index", "Login");
            }

            List<PlayList> playlists = null;
            
            SpotifyService spotifyService = new SpotifyService();
            playlists = spotifyService.GetPlaylists(token);
            
            ViewBag.PlayLists = playlists;

            return View();
        }

        public ActionResult Tracks(string idPlayList)
        {
            string token = ApiManager.GetKey(ApiManager.Spotify);
            bool hasToken = !string.IsNullOrEmpty(token);

            if (!hasToken)
            {
                return RedirectToAction("Index", "Login");
            }

            List<Track> tracks = null;
            if (hasToken)
            {
                SpotifyService spotifyService = new SpotifyService();
                tracks = spotifyService.GetPlayListTracks(token, idPlayList);
            }

            ViewBag.Tracks = tracks;
            return View();
        }

    }
}

AM_Spotify/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Objetivos do trabalho</p>

AM_Spotify/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    <p>Centro de Ensino Superior de Juiz de Fora</p>
    <p>Juiz de Fora - MG</p>
</address>

<address>
    <strong>Contato:</strong> <a href="mailto:magmapt@gmail.com">magmapt@gmail.com</a>
</address>

AM_Spotify/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Trabalho API Spotify</h1>
    <p class="lead">Aplicação ASP.NET MVC para utilização da API do Spotify</p>
</div>

<div class="row">
    <div class="col-md-4">
    </div>
</div>

AM_Spotify/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trabalho AMS </title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/LoginStyle.css")
    @Styles.Render("~/Content/font-awesome/all.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class= "login-view container">
        <h1 class="app-name">Trabalho API Spotify</h1>
        
        <a class="btn btn-success"
           href="@Url.Action("Login", "Auth")">
            <i class="fab fa-spotify"></i> LogOn Spotify
        </a>

        <p class="info-text">Criado por Lucas de Almeida Paula</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/font-awesome")
</body>
</html>

AM_Spotify/Views/PlayList/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PlayLists</h2>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th></th>
            <th>Nome</th>
            <th>Criador</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        @foreach (AM_Spotify.Models.PlayList playList in ViewBag.PlayLists)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Tracks", "PlayList", new { idPlayList = @playList.Id })">
                        <i class="fas fa-music"></i>
                    </a>
                </td>
                <td>@playList.Nome</td>
                <td>@playList.Criador</td>
                <td>@playList.Link</td>
            </tr>
        }
    </tbody>
</table>

AM_Spotify/Views/PlayList/Tracks.cshtml
@{
    ViewBag.Title = "Tracks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tracks</h2>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nome</th>
            <th>Album</th>
            <th>Artista</th>
        </tr>
    </thead>
    <tbody>
        @foreach (AM_Spotify.Models.Track track in ViewBag.Tracks)
        {
            <tr>
                <td>@track.Nome</td>
                <td>@track.Album</td>
                <td>@track.Artista</td>
            </tr>
        }
    </tbody>
</table>

AM_Spotify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trabalho API Spotify</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome/all.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">
                @Html.ActionLink("Trabalho API", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("PlayLists", "Index", "PlayList", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Sobre", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contato", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Trabalho Consumir API</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/font-awesome")
    @RenderSection("scripts", required: false)
</body>
</html>